# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-open" do
  version "2.5.0"

  on_macos do
    on_intel do
      sha256 "fe2965b1133b0e98fbcac5c4550658b5e302a1a013ec91eb320aea006a9a1300"
      url "https://github.com/zhaochunqi/git-open/releases/download/v#{version}/git-open_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "72ff768c96a163f15780ce4e9d84f0f080dfa19246ebea8506884e2c8bba604e"
      url "https://github.com/zhaochunqi/git-open/releases/download/v#{version}/git-open_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a6a9ff116b08e45f8a5a8cc898eac81de3a2530ea828346cab948d8590440c39"
      url "https://github.com/zhaochunqi/git-open/releases/download/v#{version}/git-open_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "f60266e3bc2fbbce15a7c2e4b7e4392cd2c59a268401ea7aa5537004b0ab3c22"
      url "https://github.com/zhaochunqi/git-open/releases/download/v#{version}/git-open_Linux_arm64.tar.gz"
    end
  end

  name "git-open"
  desc "Open the web URL of the Git repository"
  homepage "https://github.com/zhaochunqi/git-open"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-open"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/git-open"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Use 'git-open' command to open the web URL of your git repository.
  EOS
end
