# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-open" do
  version "2.7.1"

  on_macos do
    on_arm do
      sha256 "9cb2e4a1d799c68b6968533e4ea7064bff2ba87571191880a102c9c1dd4a7df3"
      url "https://github.com/zhaochunqi/git-open/releases/download/v#{version}/git-open_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ad60dfc090b6ce000e58e04d218aa25205d5dd36e1196d0a36890709c0eca6f3"
      url "https://github.com/zhaochunqi/git-open/releases/download/v#{version}/git-open_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7dc4bb3f400f9c64365ba644d301401d41b4e919f31fb4c80f354fd3054fade4"
      url "https://github.com/zhaochunqi/git-open/releases/download/v#{version}/git-open_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "15d1e78d1d8694053357c09928a09f082feac40bd9ee271e5deb4ad4835ec3c2"
      url "https://github.com/zhaochunqi/git-open/releases/download/v#{version}/git-open_Linux_x86_64.tar.gz"
    end
  end

  name "git-open"
  desc "Open the web URL of the Git repository"
  homepage "https://github.com/zhaochunqi/git-open"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-open"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/git-open"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Use 'git-open' command to open the web URL of your git repository.
  EOS
end
