# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-open" do
  name "git-open"
  desc "Open the web URL of the Git repository"
  homepage "https://github.com/zhaochunqi/git-open"
  version "2.2.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-open"

  on_macos do
    on_intel do
      url "https://github.com/zhaochunqi/git-open/releases/download/v#{version}/git-open_Darwin_x86_64.tar.gz"
      sha256 "c5045da11f04f75b75d491280a00fe5c4db9ce37c156813b04a0985aeaaf5a4c"
    end
    on_arm do
      url "https://github.com/zhaochunqi/git-open/releases/download/v#{version}/git-open_Darwin_arm64.tar.gz"
      sha256 "53f8f98d26c9b977991a761abfdf1a7127aa92eb7e74907d7a9fc9943decfff0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/zhaochunqi/git-open/releases/download/v#{version}/git-open_Linux_x86_64.tar.gz"
      sha256 "499e593dc5d683da69cd4cb911ff8ceedd0ef2adee7bc16ec6a0724508fd713d"
    end
    on_arm do
      url "https://github.com/zhaochunqi/git-open/releases/download/v#{version}/git-open_Linux_arm64.tar.gz"
      sha256 "87abf304172c6dee2751c80013288395c23c382e36d887f7bf91b9d8000421ca"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/git-open"]
    end
  end

  caveats do
    "Use 'git-open' command to open the web URL of your git repository."
  end

  # No zap stanza required
end
