# This file was generated by GoReleaser. DO NOT EDIT.
cask "vidsum" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "dd375c4c019953801f52bd3dfa15fc679363211ac66e13e7a9782905030d5234"
      url "https://github.com/zhaochunqi/vidsum/releases/download/v#{version}/vidsum_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c4a8f6d890096d55e0395c64898177c1d8e39f9d76ba2919c09b9e92bfccefc4"
      url "https://github.com/zhaochunqi/vidsum/releases/download/v#{version}/vidsum_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "33172795d114c270d094babb9fb70e044f3897cf846d020cb330f37038375d82"
      url "https://github.com/zhaochunqi/vidsum/releases/download/v#{version}/vidsum_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "95771b820a4c2a60b8e6a8f4414f5c40d4a25c1de5040fa9c5dd508cb292e9f8"
      url "https://github.com/zhaochunqi/vidsum/releases/download/v#{version}/vidsum_Linux_x86_64.tar.gz"
    end
  end

  name "vidsum"
  desc "Download a video's audio, transcribe it, summarize it"
  homepage "https://github.com/zhaochunqi/vidsum"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vidsum"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/vidsum"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Requires external tools: yt-dlp, ffmpeg, and a transcription engine (e.g. mlx_whisper). Configure via ~/.config/vidsum/config.toml.
  EOS
end
